version: 2.1

jobs:
  linters:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run ci:lint
      - store_test_results:
          path: ~/project/reports
      - store_artifacts:
          path: ~/project/reports
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run prestart:prod
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

orbs:
  node: circleci/node@4.1.0
workflows:
  main-pipeline:
    jobs:
      - test
      - linters
      - build:
          requires:
            - linters
            - test
