version: 2.1

jobs:
  linters:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run prestart:prod

orbs:
  node: circleci/node@3.0.0
workflows:
  main-pipeline:
    jobs:
      - node/test
      - linters
      - build:
          requires:
            - linters
            - node/test
