version: 2.1

jobs:
  linters:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run ci:lint
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run prestart:prod

orbs:
  node: circleci/node@4.1.0
workflows:
  main-pipeline:
    jobs:
      - node/test
      - linters
      - build:
          requires:
            - linters
            - node/test
