export const LISTS = 'lists'
export const MOVIES = 'movies'
export const MOVIE = 'movie'
export const DASHBOARD = 'dashboard'
export const WATCHLIST = 'watchlist'
export const FAVORITES = 'favorites'
